[dependencies]
  
[package]
  cjc-version = "1.0.0"
  compile-option = "-O2"
  description = "nothing here"
  link-option = "-lssl -lcrypto"
  name = "shadowsocks_cj"
  output-type = "static"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
[package.package-configuration."shadowsocks_cj.local"]
  output-type = "executable"
[package.package-configuration."shadowsocks_cj.remote"]
  output-type = "executable"

[target.x86_64-w64-mingw32]
  compile-option = "-lcrypt32"
  [target.x86_64-w64-mingw32.bin-dependencies]
    path-option = ["${CANGJIE_STDX_PATH}"]

[target.x86_64-unknown-linux-gnu]
  [target.x86_64-unknown-linux-gnu.bin-dependencies]
    path-option = ["${CANGJIE_STDX_PATH}"]