[dependencies]
  
[package]
  cjc-version = "0.60.5"
  compile-option = ""
  description = "nothing here"
  link-option = "-lcrypto"
  name = "shadowsocks_cj"
  output-type = "executable"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = { "shadowsocks_cj.local" = { output-type = "executable" }, "shadowsocks_cj.remote" = { output-type = "executable" } }

[target.x86_64-w64-mingw32]
  compile-option = "-lcrypt32"
  [target.x86_64-w64-mingw32.bin-dependencies]
    path-option = ["${CANGJIE_STDX_PATH}"]