name: Daily Build

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点运行
  workflow_dispatch:      # 允许手动触发

env:
  # SDK仓库配置
  LINUX_SDK_REPO: "git@gitcode.com:Cangjie/CangjieSDK-Linux-Beta.git"
  WINDOWS_SDK_REPO: "git@gitcode.com:Cangjie/CangjieSDK-Win-Beta.git"
  LINUX_SDK_TAG: "Cangjie-Linux-Canary-0.58.3"
  WINDOWS_SDK_TAG: "Cangjie-Win-Canary-0.58.3"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup GitCode SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GITCODE_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
        echo "${{ secrets.GITCODE_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        
    - name: Setup CangJie SDK
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          git clone --branch $LINUX_SDK_TAG $LINUX_SDK_REPO sdk.tar.gz
          tar -xzf sdk.tar.gz
          cd cangjie
          chmod +x envsetup.sh
          source ./envsetup.sh
        else
          git clone --branch $WINDOWS_SDK_TAG $WINDOWS_SDK_REPO sdk.tar.gz
          if [ -f "envsetup.bat" ]; then
            .\envsetup.bat
          else
            pwsh -Command "& { .\envsetup.ps1 }"
          fi
        fi
        
    - name: Build with cjpm
      run: cjpm build
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: shadowsocks_cj-${{ matrix.os }}
        path: shadowsocks_cj.zip
